services:
  - type: web
    name: buszapp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false          # você colará a URL do Neon no painel do Render
      - key: APP_URL
        sync: false          # ex: https://buszapp.onrender.com
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ROUTE_ORIGIN_LAT
        value: "-27.10597"
      - key: ROUTE_ORIGIN_LON
        value: "-52.61336"
      - key: ROUTE_DEST_LAT
        value: "-27.07171"
      - key: ROUTE_DEST_LON
        value: "-52.63635"
    healthCheckPath: /login.html
