"""adicionando colunas de cartao

Revision ID: 390ddb9c557b
Revises: 
Create Date: 2026-03-25 18:47:01.161372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390ddb9c557b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('card_holder', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('card_type')
        batch_op.drop_column('card_holder')
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###
