"""add ended_at to driver_trip

Revision ID: 425ccc6f03b9
Revises: ae45e3549d5a
Create Date: 2026-03-28 00:44:31.505497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ccc6f03b9'
down_revision = 'ae45e3549d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_trip', schema=None) as batch_op:
        batch_op.drop_column('ended_at')

    # ### end Alembic commands ###
