"""driver schedules and rating driver link

Revision ID: ae45e3549d5a
Revises: bb2b2c03438e
Create Date: 2026-03-28 00:00:17.820982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae45e3549d5a'
down_revision = 'bb2b2c03438e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_schedule', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('last_schedule', sa.String(length=5), nullable=True))

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_departure', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'driver', ['driver_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('schedule_departure')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('last_schedule')
        batch_op.drop_column('first_schedule')

    # ### end Alembic commands ###
